# Build the ColorPicker project utilizing npm and MSBuild
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: $(BuildVersionMajor).$(BuildVersionMinor).$(BuildVersionPatch).$(BuildVersionRevision)

trigger: none
  # branches:
  #   include:
  #   - master
  # paths:
  #   exclude:
  #   - *.md
  #   - *.yml

pr: none

variables:
  #BUILD VERSION INFORMATION
  BuildVersionMajor: 1
  BuildVersionMinor: 1
  BuildVersionPatch: 0
  #sets a counter for the version number changing the Major or Minor version will reset this counter
  #back to it's seed value  
  BuildVersionRevision: $[counter(format('{0}.{1}.{2}', variables['BuildVersionMajor'], variables['BuildVersionMinor'],variables['BuildVersionPatch']), 1)]

pool:
  vmImage: 'windows-latest'

#COLOR PICKER

steps:
# Step 1: Cache Global npm Modules
- task: Cache@2
  inputs:
    key: 'npm-cache | "$(Agent.OS)" | package-lock.json'
    path: $(npm_config_cache)
    cacheHitVar: NPM_GLOBAL_CACHE_RESTORED

# ColorPicker
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/ColorPicker/package-lock.json'
    path: '$(Build.SourcesDirectory)/ColorPicker/node_modules'
    cacheHitVar: CACHE_RESTORED_COLORPICKER

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_COLORPICKER'], 'true')
  inputs:
    command: 'install'
    workingDir: './ColorPicker/'

# BooleanOptionset
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/BooleanOptionset/package-lock.json'
    path: '$(Build.SourcesDirectory)/BooleanOptionset/node_modules'
    cacheHitVar: CACHE_RESTORED_BOOLEANOPTIONSET

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_BOOLEANOPTIONSET'], 'true')
  inputs:
    command: 'install'
    workingDir: './BooleanOptionset/'

# Example: BingMapsGrid
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/BingMapsGrid/package-lock.json'
    path: '$(Build.SourcesDirectory)/BingMapsGrid/node_modules'
    cacheHitVar: CACHE_RESTORED_BINGMAPSGRID

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_BINGMAPSGRID'], 'true')
  inputs:
    command: 'install'
    workingDir: './BingMapsGrid/'

# Example: AzureMapsGrid
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/AzureMapsGrid/package-lock.json'
    path: '$(Build.SourcesDirectory)/AzureMapsGrid/node_modules'
    cacheHitVar: CACHE_RESTORED_AZUREMAPSGRID

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_AZUREMAPSGRID'], 'true')
  inputs:
    command: 'install'
    workingDir: './AzureMapsGrid/'

# Example: WorldDaylightMap
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/WorldDaylightMap/package-lock.json'
    path: '$(Build.SourcesDirectory)/WorldDaylightMap/node_modules'
    cacheHitVar: CACHE_RESTORED_WORLDDAYLIGHTMAP

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_WORLDDAYLIGHTMAP'], 'true')
  inputs:
    command: 'install'
    workingDir: './WorldDaylightMap/'

# DetailListGrid
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/DetailListGrid/package-lock.json'
    path: '$(Build.SourcesDirectory)/DetailListGrid/node_modules'
    cacheHitVar: CACHE_RESTORED_DETAILLISTGRID

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_DETAILLISTGRID'], 'true')
  inputs:
    command: 'install'
    workingDir: './DetailListGrid/'

# Calendar
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/Calendar/package-lock.json'
    path: '$(Build.SourcesDirectory)/Calendar/node_modules'
    cacheHitVar: CACHE_RESTORED_CALENDAR

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_CALENDAR'], 'true')
  inputs:
    command: 'install'
    workingDir: './Calendar/'

# CanvasFileDownloader
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/CanvasFileDownloader/package-lock.json'
    path: '$(Build.SourcesDirectory)/CanvasFileDownloader/node_modules'
    cacheHitVar: CACHE_RESTORED_CANVASFILEDOWNLOADER

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_CANVASFILEDOWNLOADER'], 'true')
  inputs:
    command: 'install'
    workingDir: './CanvasFileDownloader/'

# CanvasFileUploader
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/CanvasFileUploader/package-lock.json'
    path: '$(Build.SourcesDirectory)/CanvasFileUploader/node_modules'
    cacheHitVar: CACHE_RESTORED_CANVASFILEUPLOADER

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_CANVASFILEUPLOADER'], 'true')
  inputs:
    command: 'install'
    workingDir: './CanvasFileUploader/'

# RotationalImage
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/RotationalImage/package-lock.json'
    path: '$(Build.SourcesDirectory)/RotationalImage/node_modules'
    cacheHitVar: CACHE_RESTORED_ROTATIONALIMAGE

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_ROTATIONALIMAGE'], 'true')
  inputs:
    command: 'install'
    workingDir: './RotationalImage/'

# RuntimeInfo
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/RuntimeInfo/package-lock.json'
    path: '$(Build.SourcesDirectory)/RuntimeInfo/node_modules'
    cacheHitVar: CACHE_RESTORED_RUNTIMEINFO

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_RUNTIMEINFO'], 'true')
  inputs:
    command: 'install'
    workingDir: './RuntimeInfo/'

# PDFFormFillCanvas
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/PDFFormFillCanvas/package-lock.json'
    path: '$(Build.SourcesDirectory)/PDFFormFillCanvas/node_modules'
    cacheHitVar: CACHE_RESTORED_PDFFORMFILLCANVAS

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_PDFFORMFILLCANVAS'], 'true')
  inputs:
    command: 'install'
    workingDir: './PDFFormFillCanvas/'

# Frame
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/Frame/package-lock.json'
    path: '$(Build.SourcesDirectory)/Frame/node_modules'
    cacheHitVar: CACHE_RESTORED_FRAME

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_FRAME'], 'true')
  inputs:
    command: 'install'
    workingDir: './Frame/'

# DadJoke
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/DadJoke/package-lock.json'
    path: '$(Build.SourcesDirectory)/DadJoke/node_modules'
    cacheHitVar: CACHE_RESTORED_DADJOKE

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_DADJOKE'], 'true')
  inputs:
    command: 'install'
    workingDir: './DadJoke/'

# DocxTemplatesCanvas
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/DocxTemplatesCanvas/package-lock.json'
    path: '$(Build.SourcesDirectory)/DocxTemplatesCanvas/node_modules'
    cacheHitVar: CACHE_RESTORED_DOCXTEMPLATESCANVAS

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_DOCXTEMPLATESCANVAS'], 'true')
  inputs:
    command: 'install'
    workingDir: './DocxTemplatesCanvas/'

# PowerPagesFileManager
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/PowerPagesFileManager/package-lock.json'
    path: '$(Build.SourcesDirectory)/PowerPagesFileManager/node_modules'
    cacheHitVar: CACHE_RESTORED_POWERPAGESFILEMANAGER

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_POWERPAGESFILEMANAGER'], 'true')
  inputs:
    command: 'install'
    workingDir: './PowerPagesFileManager/'

# RestrictedChoice
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/RestrictedChoice/package-lock.json'
    path: '$(Build.SourcesDirectory)/RestrictedChoice/node_modules'
    cacheHitVar: CACHE_RESTORED_RESTRICTEDCHOICE

- task: Npm@1
  condition: ne(variables['CACHE_RESTORED_RESTRICTEDCHOICE'], 'true')
  inputs:
    command: 'install'
    workingDir: './RestrictedChoice/'

#PowerApps controls can be build using MSBuild and do not require the PCF CLI to be downloaded.
#The build command will utilize NuGet to go out and get all the resource packages it needs.
- task: MSBuild@1
  inputs:
    solution: '**/*.cdsproj'
    msbuildArguments: '/t:build /p:Configuration=Release /restore'

#Copy the solution files to the build artifacts directory.
- task: CopyFiles@2
  inputs:
    SourceFolder: './ColorPicker/ColorPicker/ControlPicker/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- powershell: |
    Rename-Item -Path "$(Build.ArtifactStagingDirectory)/ControlPicker_managed.zip" -NewName "ColorPicker_managed.zip"      
  displayName: 'Rename Control Picker to Color Picker'

- powershell: |
    Rename-Item -Path "$(Build.ArtifactStagingDirectory)/ControlPicker.zip" -NewName "ColorPicker.zip"      
  displayName: 'Rename Control Picker to Color Picker'

- task: CopyFiles@2
  inputs:
    SourceFolder: './BooleanOptionset/BooleanOptionset/BooleanOptionsetControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './BingMapsGrid/BingMapsGrid/BingMapsGridControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './AzureMapsGrid/AzureMapsGrid/AzureMapsGridControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './WorldDaylightMap/Solution/RAWWorldDaylightMap/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './DetailListGrid/DetailListGrid/DetailListGridControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './Calendar/Calendar/CalendarControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './CanvasFileDownloader/Solution/CanvasFileDownloaderControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './CanvasFileUploader/Solution/CanvasFileUploaderComponent/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './RotationalImage/Solution/RotationalImageComponent/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './RuntimeInfo/Solution/RuntimeInfoComponent/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './PDFFormFillCanvas/Solutions/RAWPDFFormFillCanvas/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './DadJoke/Solution/RAW!DadJoke/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './Frame/Solution/RAWframe/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './DocxTemplatesCanvas/Solution/RAWDocxTemplatesCanvas/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './PowerPagesFileManager/Solution/PowerPagesFileManagerSolution/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: './RestrictedChoice/Solution/RestrictedChoiceControl/bin/Release/'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

#Publish the build artifacts.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#GitHub Release
- task: GitHubRelease@1
  condition: and(succeeded(), eq(variables['Release'], true))
  inputs:
    gitHubConnection: 'github.com_rwilson504'
    repositoryName: 'rwilson504/PCFControls'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
